const express = require('express');
const app = express();
const path = require('path');
const cors = require('cors');
// const products = require('./src/data/products.cjs');

app.use(express.static(path.join(__dirname, 'src')));
app.use(express.json());
app.use(cors());

const product1 = 'http://localhost:3000/assets/product1.png';
const product1a = 'http://localhost:3000/assets/product1a.png';
const product1b = 'http://localhost:3000/assets/product1b.png';
const product1c = 'http://localhost:3000/assets/product1c.png';
const product1d = 'http://localhost:3000/assets/product1d.png';
const product2 = 'http://localhost:3000/assets/product2.png';
const product2a = 'http://localhost:3000/assets/product2a.png';
const product2b = 'http://localhost:3000/assets/product2b.png';
const product2c = 'http://localhost:3000/assets/product2c.png';
const product2d = 'http://localhost:3000/assets/product2d.png';
const product3 = 'http://localhost:3000/assets/product3.png';
const product3a = 'http://localhost:3000/assets/product3a.png';
const product3b = 'http://localhost:3000/assets/product3b.png';
const product3c = 'http://localhost:3000/assets/product3c.png';
const product3d = 'http://localhost:3000/assets/product3d.png';
const product4 = 'http://localhost:3000/assets/product4.png';
const product4a = 'http://localhost:3000/assets/product4a.png';
const product4b = 'http://localhost:3000/assets/product4b.png';
const product4c = 'http://localhost:3000/assets/product4c.png';
const product4d = 'http://localhost:3000/assets/product4d.png';

const products = [
    {
        id: 1, //in a real dataset I'd use the id generated by the database/backend or use a library like uuid
        mainImage: product1,
        brand: 'Off-White',
        name: 'Out Of Office "Ooo" sneakers',
        price: 775,
        detailImage: product1d,
        carouselImages: [product1a, product1b, product1c],
    },
    {
        id: 2,
        mainImage: product2,
        brand: 'Nike',
        name: 'Nike Gamma Force',
        price: 200,
        detailImage: product2d,
        carouselImages: [product2a, product2b, product2c],
    },
    {
        id: 3,
        mainImage: product3,
        brand: 'Nike',
        name: 'Cosmic Unity 3',
        price: 160,
        detailImage: product3d,
        carouselImages: [product3a, product3b, product3c],
    },
    {
        id: 4,
        mainImage: product4,
        brand: 'adidas',
        name: 'DAILY 3.0 SHOES',
        price: 98.99,
        detailImage: product4d,
        carouselImages: [product4a, product4b, product4c],
    },
];

app.get('/api/products', (req, res) => {
   return res.json(products);
});

app.get('/api/products/:id', (req, res) => {
    const productId = parseInt(req.params.id);
    const product = products.find((p) => p.id === productId);

    if (!product) {
        return res.status(404).json({ error: 'Product not found' });
    }

    res.json(product);
});

const port = 3000;
app.listen(port, () => {
    console.log(`Server is running on http://localhost:${port}`);
});