import product1 from '../assets/product1.png'
import product1a from '../assets/product1a.png';
import product1b from '../assets/product1b.png';
import product1c from '../assets/product1c.png';
import product1d from '../assets/product1d.png';
import product2 from '../assets/product2.png';
import product2a from '../assets/product2a.png';
import product2b from '../assets/product2b.png';
import product2c from '../assets/product2c.png';
import product2d from '../assets/product2d.png';
import product3 from '../assets/product3.png';
import product3a from '../assets/product3a.png';
import product3b from '../assets/product3b.png';
import product3c from '../assets/product3c.png';
import product3d from '../assets/product3d.png';
import product4 from '../assets/product4.png';
import product4a from '../assets/product4a.png';
import product4b from '../assets/product4b.png';
import product4c from '../assets/product4c.png';
import product4d from '../assets/product4d.png';

const products = [
    {
        id: 1, //in a real dataset I'd use the id generated by the database/backend or use a library like uuid
        mainImage: product1,
        brand: 'Off-White',
        name: 'Out Of Office "Ooo" sneakers',
        price: 775,
        detailImage: product1d,
        carouselImages: [product1a, product1b, product1c],
    },
    {
        id: 2,
        mainImage: product2,
        brand: 'Nike',
        name: 'Nike Gamma Force',
        price: 200,
        detailImage: product2d,
        carouselImages: [product2a, product2b, product2c],
    },
    {
        id: 3,
        mainImage: product3,
        brand: 'Nike',
        name: 'Cosmic Unity 3',
        price: 160,
        detailImage: product3d,
        carouselImages: [product3a, product3b, product3c],
    },
    {
        id: 4, 
        mainImage: product4,
        brand: 'adidas',
        name: 'DAILY 3.0 SHOES',
        price: 98.99,
        detailImage: product4d,
        carouselImages: [product4a, product4b, product4c],
    },
];

export default products;